# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'javascript'
    groups:
      cmp-app:
        update-types:
          - 'minor'
          - 'patch'
  - package-ecosystem: 'npm'
    directory: '/cdk'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'javascript'
    groups:
      cdk:
        update-types:
          - 'minor'
          - 'patch'
  - package-ecosystem: 'npm'
    directory: '/monitoring'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'javascript'
    groups:
      monitoring:
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: 'inquirer'
      - dependency-name: '@types/inquirer'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
      - 'github_actions'
    groups:
      github_action:
        patterns:
          - '*'
