# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'cmp_app_group'
    groups:
      cmp-app:
        patterns:
          - '*'
  - package-ecosystem: 'npm'
    directory: '/cdk'
    schedule:
      interval: 'weekly'
    labels:
      - 'cdk_group'
    groups:
      cdk:
        patterns:
          - '*'
  - package-ecosystem: 'npm'
    directory: '/monitoring'
    schedule:
      interval: 'weekly'
    labels:
      - 'monitoring_group'
    groups:
      monitoring:
        patterns:
          - '*'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      patch-minor-ga:
        update-types:
          - 'patch'
          - 'minor'
