codecov:
    require_ci_to_pass: no

coverage:
    precision: 2
    round: down
    range: '70...100'
    status:
        patch:
            default:
                target: auto
                threshold: 5%
                base: auto

parsers:
    gcov:
        branch_detection:
            conditional: yes
            loop: yes
            method: no
            macro: no

comment: false
github_checks:
    annotations: true
