codecov:
    require_ci_to_pass: no

coverage:
    precision: 2
    round: down
    range: '70...100'
    status:
        patch:
            default:
                # basic
                target: auto
                threshold: 5%
                flags:
                    - 'unit'
                paths:
                    - 'src'

parsers:
    gcov:
        branch_detection:
            conditional: yes
            loop: yes
            method: no
            macro: no

comment:
    layout: 'files'
    behavior: new
    require_changes: no

github_checks:
    annotations: true
