name: CI Monitoring
on:
  push:
    branches-ignore:
      - 'gh-pages'

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      # Setup AWS credentials to enable uploading to S3 for Riff-Raff.
      # See https://github.com/aws-actions/configure-aws-credentials
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: yarn
          cache-dependency-path: |
            yarn.lock
            monitoring/yarn.lock
            cdk/yarn.lock

      - name: Install Root dependencies
        run: yarn --frozen-lockfile

      - name: Lambda Install CDK dependencies
        working-directory: './monitoring'
        run: yarn --frozen-lockfile

      - name: Lambda lint
        working-directory: './monitoring'
        run: yarn lint

      - name: Lambda Build
        working-directory: './monitoring'
        run: yarn build

      - name: CDK Install CDK dependencies
        working-directory: './cdk'
        run: yarn --frozen-lockfile

      - name: CDK Test
        working-directory: './cdk'
        run: yarn test

      - name: CDK lint
        working-directory: './cdk'
        run: yarn lint

      - name: CDK Build
        working-directory: './cdk'
        run: yarn build

      - name: CDK Synth
        working-directory: './cdk'
        run: yarn synth

      - name: Generate riff-raff artifacts
        run: yarn ci:monitoring
