name: Continuous integration
on:
    push:
        branches-ignore:
            - 'gh-pages'
jobs:
    test:
        name: Validate
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            
            - uses: bahmutov/npm-install@v1
              
            - name: Run unit tests
              run: yarn test:unit
              
            - name: Lint files
              run: yarn lint
              
            - name: Run type checks
              run: yarn tsc

