name: Continuous integration
on:
    push:
        branches-ignore:
            - 'gh-pages'
jobs:
    test:
        name: Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - uses: actions/cache@v1.1.2
              with:
                path: echo "$(yarn cache dir)"
                key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                restore-keys: |
                  ${{ runner.os }}-yarn-
            - run: yarn
            - run: yarn test:unit
            - run: yarn lint
            - run: yarn tsc

