name: CI
on:
    push:
        branches-ignore:
            - 'gh-pages'
jobs:
    test:
        name: Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2.1.1
              with:
                  node-version: 12

            - name: Install dependencies
              uses: bahmutov/npm-install@v1

            - name: Run unit tests
              uses: mattallty/jest-github-action@v1.0.3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  test-command: 'yarn test --coverage --ci'
    lint:
        name: Linting
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2.1.1
              with:
                  node-version: 12

            - name: Install dependencies
              uses: bahmutov/npm-install@v1

            - name: Lint files
              run: yarn lint
    types:
        name: Types
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2.1.1
              with:
                  node-version: 12

            - name: Install dependencies
              uses: bahmutov/npm-install@v1

            - name: Check types
              run: yarn tsc
