name: CI
on:
    push:
        branches-ignore:
            - 'gh-pages'

jobs:
    test-unit:
        name: Unit tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            # based on https://github.com/actions/setup-node/issues/32#issuecomment-539794249
            - name: Read .nvmrc
                run: echo ::set-output name=NVMRC::$(cat .nvmrc)
                id: nvm

            - name: Setup node
                uses: actions/setup-node@v2.1.2
                with:
                node-version: '${{ steps.nvm.outputs.NVMRC }}'

            - name: Install dependencies
              uses: bahmutov/npm-install@v1

            - name: Run unit tests
              uses: mattallty/jest-github-action@v1.0.3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  test-command: 'yarn test:unit'

            - name: Check coverage
              uses: codecov/codecov-action@v1.0.13

    test-e2e:
        name: e2e tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            # based on https://github.com/actions/setup-node/issues/32#issuecomment-539794249
            - name: Read .nvmrc
                run: echo ::set-output name=NVMRC::$(cat .nvmrc)
                id: nvm

            - name: Setup node
                uses: actions/setup-node@v2.1.2
                with:
                node-version: '${{ steps.nvm.outputs.NVMRC }}'

            - name: Install dependencies
              uses: bahmutov/npm-install@v1

            - name: Run e2e tests on dist with Cypress
              run: yarn test:e2e
    lint:
        name: Linting
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            # based on https://github.com/actions/setup-node/issues/32#issuecomment-539794249
            - name: Read .nvmrc
                run: echo ::set-output name=NVMRC::$(cat .nvmrc)
                id: nvm

            - name: Setup node
                uses: actions/setup-node@v2.1.2
                with:
                node-version: '${{ steps.nvm.outputs.NVMRC }}'

            - name: Install dependencies
              uses: bahmutov/npm-install@v1

            - name: Lint files
              run: yarn lint
    types:
        name: Types
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            # based on https://github.com/actions/setup-node/issues/32#issuecomment-539794249
            - name: Read .nvmrc
                run: echo ::set-output name=NVMRC::$(cat .nvmrc)
                id: nvm

            - name: Setup node
                uses: actions/setup-node@v2.1.2
                with:
                node-version: '${{ steps.nvm.outputs.NVMRC }}'

            - name: Install dependencies
              uses: bahmutov/npm-install@v1

            - name: Check types
              run: yarn tsc
