name: Build and/or Release CMP

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up pnpm 8.x
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build package
        run: pnpm build

      - name: Check dist folder for files
        run: ./scripts/check-build-folders

      - name: Save build
        if: github.ref == 'refs/heads/main' || github.event.label.name == '[beta] @guardian/consent-management-platform'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  release:
    name: Release
    needs: [build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write # in order to write labels to main branch?
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up pnpm 8.x
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Fetch build
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Release
        uses: changesets/action@v1
        with:
          publish: pnpm run changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0

  release-beta:
    name: Release Beta
    needs: [build]
    if: github.event.label.name == '[beta] @guardian/consent-management-platform'
    runs-on: ubuntu-latest
    permissions:
      contents: write # in order to write labels to main branch?
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
      issues: write
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up pnpm 8.x
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Fetch build
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Version
        run: pnpm changeset version --snapshot beta

      - name: Create Release
        uses: changesets/action@v1
        id: changeset
        with:
          publish: pnpm run changeset publish --tag beta
          commit: Beta Release
          title: Beta Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/github-script@v6
        if: steps.changeset.outputs.published == 'true'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const publishedPackages = ${{ steps.changeset.outputs.publishedPackages }};
            const version = publishedPackages[0].version;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 ${version} published to npm as a beta release`
            })
