name: Publish Beta Package

# This workflow is triggered on a label being added to a PR, and will publish a beta version of the bundle to npm
# Use `yarn changeset add` to add a new change
# This action will release the changeset as a pre-release, and add a comment to the PR with the version number
on:
  pull_request:
    types: [labeled]

permissions: write-all

jobs:
  has-permission:
    name: Check permissions
    runs-on: ubuntu-latest
    steps:
      - name: 'Check if user has admin access'
        uses: 'lannonbr/repo-permission-check-action@2.0.2'
        with:
          permission: 'admin'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-app:
    name: Build CMP App
    uses: ./.github/workflows/app-build.yml
