name: CI
on:
  push:
    branches-ignore:
      - 'gh-pages'

jobs:
  run-tests:
    name: Run tests
    uses: ./.github/workflows/cmp-run-tests.yml
    permissions:
      checks: write
      pull-requests: write
      contents: write
  run-checks:
    name: Run checks
    uses: ./.github/workflows/cmp-run-checks.yml
  build:
    name: Build CMP
    needs: [run-tests, run-checks]
    uses: ./.github/workflows/cmp-build.yml
    permissions:
      checks: write
      pull-requests: write
      contents: write
      id-token: write
