name: Execute Daily Test
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up pnpm 8.x
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies at root (./)
        run: pnpm install --frozen-lockfile

      - name: Test vendor list
        run: pnpm test:vendor-list
