name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: guardian/actions-setup-node@main

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: yarn build

      - name: Deploy
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          BUILD_DIR: 'test-page/dist/'
        uses: guardian/ghpages@v0.4.0
