name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: pnpm

      - name: Install dependencies
        run: pnpm --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          pnpm github-pages-deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
