name: Deploy to GitHub Pages
on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2.1.1
              with:
                  node-version: 12
            - name: build
              run: |
                  yarn
                  yarn gh-pages:build
            - name: deploy
              env:
                  GH_PAT: ${{ secrets.GH_PAT }}
                  BUILD_DIR: '.gh-pages/'
              uses: maxheld83/ghpages@v0.3.0
