name: Snyk PR

on:
  pull_request:
    paths:
      - '**/package.json'

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk-pr.yml@main
    with:
      ORG: guardian-consent
      SEVERITY_THRESHOLD: critical
      node-version-file: './monitoring/.nvmrc'
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
