name: Snyk PR

on:
  pull_request:
    paths:
      - "**/package.json"

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk-pr.yml@main
    with:
      ORG: guardian-consent
      SEVERITY_THRESHOLD: critical
      NODE_VERSION_FILE: "./monitoring/.nvmrc"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
