name: Snyk

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@revert-39-rk/pin-snyk-to-fix-in-main
    with:
      SKIP_SBT: true
      DEBUG: true
      ORG: guardian-consent
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
